#soon ...
#sudo: false
language: python
python:
    - "2.7"
env:
    - CKANVERSION=2.8
    - CKANVERSION=2.3
install:
    - bash bin/travis-build.bash
services:
    - redis-server
    - postgresql
script: sh bin/travis-run.sh
dist: trusty
notifications:
  email:
    on_success: never  # default: change
    on_failure: always # default: always
