version: 2
jobs:
  lint:
    docker:
      - image: circleci/python:2.7.18
    steps:
      - run:
          name: lint code
          command: |
            pip install --upgrade pip
            pip install flake8
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics 
  test_local_docker:
    working_directory: ~/ckanext-datajson
    machine: 
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build and test 
          command: |
            docker-compose build
            docker-compose up -d
            sleep 40
            docker-compose logs db
            docker-compose logs ckan
            docker-compose exec ckan /bin/bash -c "nosetests --ckan --with-pylons=src_extensions/datajson/docker_test.ini src_extensions/datajson/"
          
  build_ckan_28:
    working_directory: ~/ckanext-datajson
    machine:
      image: circleci/classic:201708-01
      # image: circleci/postgres:9.6-alpine
    environment:
      CKANVERSION=2.8
    steps:
      - checkout
      - run:
          name: install
          command: bin/travis-build.bash
      - run:
          name: test
          command: bin/travis-run.sh
  build_ckan_23:
    working_directory: ~/ckanext-datajson
    machine:
      image: circleci/classic:201708-01
    environment:
      CKANVERSION=2.3
    steps:
      - checkout
      - run:
          name: install
          command: bin/travis-build.bash
      - run:
          name: test
          command: bin/travis-run.sh

  build_gsa_ckan_inventory:
    working_directory: ~/ckanext-datajson
    machine:
      image: circleci/classic:201708-01
    environment:
      CKANVERSION=inventory
    steps:
      - checkout
      - run:
          name: install
          command: bin/travis-build-inventory.bash
      - run:
          name: test
          command: bin/travis-run-inventory.sh
  
  build_gsa_ckan_datagov:
    working_directory: ~/ckanext-datajson
    machine:
      image: circleci/classic:201708-01
    environment:
      CKANVERSION=datagov
    steps:
      - checkout
      - run:
          name: install
          command: bin/travis-build.bash
      - run:
          name: test
          command: bin/travis-run.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - test_local_docker:
          requires:
            - lint
      - build_ckan_28:
          requires:
            - lint
      - build_ckan_23:
          requires:
            - lint
      - build_gsa_ckan_inventory:
          requires:
            - lint
      - build_gsa_ckan_datagov:
          requires:
            - lint
