version: 2.1
jobs:
  build:
    working_directory: ~/ckanext-datajson
    machine:
      image: circleci/classic:201708-01
    environment:
      CKANVERSION=2.8
    docker:
      - image: circleci/postgres:9.6-alpine
    steps:
      - checkout
      - run:
          name: where am I
          command: pwd && ls -la
      - run:
          name: install
          command: bin/travis-build.bash
      - run:
          name: test
          command: bin/travis-run.sh
