version: 2
jobs:
  build:
    docker:
      # - image: circleci/python:2.7
      - image: ubuntu-1404:201712-01
    environment:
      CKANVERSION=2.8
    steps:
      - run:
          name: install
          command: bin/travis-build.bash
      - run:
          name: test
          command: bin/travis-run.sh
