version: 2
jobs:
  lint:
    docker:
      - image: circleci/python:2.7.18
    steps:
      - run:
          name: lint code
          command: |
            pip install --upgrade pip
            pip install flake8
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics 
  test_local_docker:
    working_directory: ~/ckanext-datajson
    machine: 
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            set -x
            sudo curl -L "https://github.com/docker/compose/releases/download/1.25.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version
      - run:
          name: Start CKAN
          command: |
            docker-compose build
            docker-compose up -d
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait http://localhost:5000/dataset -timeout 120s
      - run:
          name: Run ckanext-datajson Tests
          command: |
            docker-compose exec ckan /bin/bash -c "nosetests --ckan --with-pylons=src_extensions/datajson/docker_test.ini src_extensions/datajson/"
  build_ckan_28:
    working_directory: ~/ckanext-datajson
    machine:
      image: circleci/classic:201708-01
      # image: circleci/postgres:9.6-alpine
    environment:
      CKANVERSION=2.8
    steps:
      - checkout
      - run:
          name: install
          command: bin/travis-build.bash
      - run:
          name: test
          command: bin/travis-run.sh
  build_ckan_23:
    working_directory: ~/ckanext-datajson
    machine:
      image: circleci/classic:201708-01
    environment:
      CKANVERSION=2.3
    steps:
      - checkout
      - run:
          name: install
          command: bin/travis-build.bash
      - run:
          name: test
          command: bin/travis-run.sh

  build_gsa_ckan_inventory:
    working_directory: ~/ckanext-datajson
    machine:
      image: circleci/classic:201708-01
    environment:
      CKANVERSION=inventory
    steps:
      - checkout
      - run:
          name: install
          command: bin/travis-build-inventory.bash
      - run:
          name: test
          command: bin/travis-run-inventory.sh
  
  build_gsa_ckan_datagov:
    working_directory: ~/ckanext-datajson
    machine:
      image: circleci/classic:201708-01
    environment:
      CKANVERSION=datagov
    steps:
      - checkout
      - run:
          name: install
          command: bin/travis-build.bash
      - run:
          name: test
          command: bin/travis-run.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      - test_local_docker:
          requires:
            - lint
      - build_ckan_28:
          requires:
            - lint
      - build_ckan_23:
          requires:
            - lint
      - build_gsa_ckan_inventory:
          requires:
            - lint
      - build_gsa_ckan_datagov:
          requires:
            - lint