version: 2
jobs:
  build:
    machine:
      - image: circleci/classic:201708-01
    environment:
      CKANVERSION=2.8
    steps:
      - run:
          name: install
          command: bin/travis-build.bash
      - run:
          name: test
          command: bin/travis-run.sh
